#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /volumio/app/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp   --name 'aalabpi2' --backend alsa --device volume --disable-audio-cache --initial-volume 85
